### ISSUE TITLE
Review necessity of Bower & wiredep

### ISSUE THREAD

**Issue by carwin** [Lullabot/windup#30]
I don't think Bower or wiredep provide very much to this project, at least not enough that it should be considered a part of our default setup for new projects.

Here's what we introduce with Bower & wiredep:
 - An extra package manager
 - An extra dependency
 - An extra configuration file
 - Moar directories

In my opinion we should just drop both and just add things to our projects like we've always done.

**Comment by krisbulman** [comment]
Yeah, it also hasn't been put through the paces of a full on project yet that I know of, without it being fully tested and a great value, i see little need to add the extra dependancies on a "bare bones" theme.

**Comment by justafish** [comment]
To summarise some thoughts from IRC from myself, @fender and @mdrummond

* Knowing the origin and version of external dependencies is good
* External dependencies aren't checked into the repo
* It solves the same problems as say, composer or npm
* It's already been used on lullabot projects, as well as being an extremely popular tool outside of Drupal-land
* It's available, but you don't have to use it

**Comment by justafish** [comment]
To summarise some thoughts from IRC from myself, @fender and @mdrummond

* Knowing the origin and version of external dependencies is good
* External dependencies aren't checked into the repo
* It solves the same problems as say, composer or npm
* It's already been used on lullabot projects, as well as being an extremely popular tool outside of Drupal-land
* It's available, but you don't have to use it

**Comment by justafish** [comment]
I discussed this with @carwin yesterday, but just adding it here...
The reason you wouldn't want to use npm for managing these is that npm has a nested dependency structure, where as Bower is flat. This means that each module you fetch with npm will have it's dependencies self contained within itself. Got two modules that require jQuery? You now have two copies of jQuery, maybe even at different versions.

**Comment by carwin** [comment]
After talking with @justafish and others I'm fine with leaving this in. Thanks for all the input.
