### ISSUE TITLE
Best practices readme(s)

### ISSUE THREAD

**Issue by krisbulman** [Lullabot/windup#31]
We need to beef out the readme(s) on best practices. 

* Proper uses of selector naming conventions
* Enforcing modularity of CSS components
* Warn that extends not to be used across partials (there are still problems with extends in libsass too)
* Keep theme name the same on new projects, only create variations of it (to avoid the same name as the project, or really dumb on the fly naming)
* Warn about bloating your tooling (crazy amounts of dependancies causing compile performance, etc)
* etc

**Comment by krisbulman** [comment]
//cc @q0rban

**Comment by carwin** [comment]
- Proper uses of selector naming conventions
   - On new projects I typically write out the project's conventions for this sort of thing at `scss/README.md`. I can whip up a "typical" one to add to this repo as a starting place, but conventions may vary by project as needed.
 - Enforcing modularity of CSS components
  - Can someone elaborate on "enforcing"? 
 - Warn that extends not to be used across partials (there are still problems with extends in libsass too)
  - This will be in the starter project conventions I'm putting together. 
 - Keep theme name the same on new projects, only create variations of it (to avoid the same name as the project, or really dumb on the fly naming)
  - The theme name can and should be flexible, it has absolutely no bearing on anything. I disagree that we should enforce anything here. If you want to leave it as "windup" in your project, that's up to you, but this is a _starter theme_.
 - Warn about bloating your tooling (crazy amounts of dependancies causing compile performance, etc)
  - The toolchain is bloated and annoying, see Issue #30. I'd love to trim it back by a lot. Open specific tickets good sirs and madams.

**Comment by krisbulman** [comment]
- Proper uses of selector naming conventions
   - On new projects I typically write out the project's conventions for this sort of thing at `scss/README.md`. I can whip up a "typical" one to add to this repo as a starting place, but conventions may vary by project as needed.
     - Could you give me an example of a deviation of naming that would be project specific? I'd be happy with some basic examples, a reference to the D8 CSS architecture docs. 
 - Enforcing modularity of CSS components
  - Can someone elaborate on "enforcing"? 
     - Sorry, didn't mean to state it so strictly. "recommend" or "suggest" might suit your fancy?
 - Warn that extends not to be used across partials (there are still problems with extends in libsass too)
  - This will be in the starter project conventions I'm putting together. 
    - Yeah, cross extending *between components* allows for ease of component removal and refactoring. I have yet to see an example of how it's at all useful to cross extend and not a maintainability nightmare. 
 - Keep theme name the same on new projects, only create variations of it (to avoid the same name as the project, or really dumb on the fly naming)
  - The theme name can and should be flexible, it has absolutely no bearing on anything. I disagree that we should enforce anything here. If you want to leave it as "windup" in your project, that's up to you, but this is a _starter theme_.
 - Warn about bloating your tooling (crazy amounts of dependancies causing compile performance, etc)
  - The toolchain in windup is bloated and annoying, see Issue #30. I'd love to trim it back by a lot. Open specific tickets good sirs and madams.

**Comment by q0rban** [comment]
The theme name does have bearing on things. The past two Lullabot projects I've been on have had the theme named after the project, which then precludes there being a module for the project that can declare an API for the project. My only thought on theme naming is for the theme to *not* be named the same as the project.

**Comment by carwin** [comment]
> Could you give me an example of a deviation of naming that would be project specific? I'd be happy with some basic examples and a reference to the D8 CSS architecture docs. 

I meant that the conventions document itself may vary by project. Some projects need comments at the top of each component partial for living style guides, etc...

> Sorry, didn't mean to state it so strictly. "recommend" or "suggest" might suit your fancy?

Either of those words are fine, I'm just not quite sure how we state "Your components should be modular" any further. We already break out everything into really specific directories and each of those has it's own README explaining what goes in there. The entire concept of components seems modular to me, but maybe I need to think about it from a different angle. Suggestions appreciated.

> Yeah, cross extending *between components* allows for ease of component removal and refactoring. I have yet to see an example of how it's at all useful to cross extend and not a maintainability nightmare. 

I pretty much dislike all extending in general with one situational exception: When you cannot control the markup of a component, but you still want to plan out the component classes according to our conventions. In that situation, I like to write out all my classes as `%placeholders {}` and then `@extend` those placeholders onto the ugly selectors at the bottom of the document. Either way, no cross-file extending.

> Perhaps suggest to just name it something other than the name of the project if you do choose to name it?

Of course we can do that, I just don't see the point.

**Comment by carwin** [comment]
@q0rban I don't quite understand that situation because I haven't been in it before, but if that's really the case we can throw that in somewhere.

**Comment by q0rban** [comment]
@carwin for example, on Syfy the theme is named `syfy`. This means that we can't have a syfy.module that has `syfy_` prefixed functions in it. Instead, if we want to declare an API for the project, we have to use some other prefix, such as `syfy_global_` or something, which means that all API functions then get `syfy_global_` at the front of it. It's mostly cosmetic—just a pet peeve of mine, that's all.

**Comment by davereid** [comment]
I've run into the same case as @q0rban before. It makes more sense to me (with a back end developer basis) to reserve the project name for either the 'site' module or install profile. All the major examples of other Drupal sites out there generally don't use the project name as the theme name.

whitehouse.gov = framedynamic.theme
weatherchannel.com = radix.theme

**Comment by carwin** [comment]
While I agree that's annoying, I don't think this is the right place to enforce an internal policy like this since Windup is a public project.

**Comment by davereid** [comment]
Definitely.

**Comment by krisbulman** [comment]
@carwin Can we not just add a warning that namespacing a theme the same name as the project can cause issues, such as example example example

**Comment by carwin** [comment]
@krisbulman yeah, that's pretty much what I was suggesting in IRC. I think that's as far as we could go with it here.
