### ISSUE TITLE
Can this be used with Stylus Preprocessor ?

### ISSUE THREAD

**Issue by IbnSaeed** [Lullabot/windup#34]
Hello

I want to use a drupal theme with stylus support, does windup support it ? or are there any necessary steps i need to take in order to make it work with stylus css instead of Sass. 

I really dont want ruby dependency

**Comment by carwin** [comment]
I'll just post @krisbulman's response to this question when you asked it in Gitter so we have it saved for the future:

> While you could essentially just rip out libsass, wiredep and replace the sass partials on your own, windup was not built with stylus in mind. Out of the box, windup uses libsass.

That said, I think our documentation still says we're using Ruby Sass. So that should be updated.
