### ISSUE TITLE
Wiredep not updating .info file

### ISSUE THREAD

**Issue by fender** [Lullabot/windup#35]
I've just set up windup and followed installation instructions (i.e. `npm/bower install`) and am having trouble with the `grunt wiredep` command.

I ran:
```
bower install susy --save
grunt wiredep
```

Susy is installed correctly with a reference listed in `_vendor.scss` but `windup.info` doesn't seem to have changed.

**Comment by justafish** [comment]
@fender That dependency will get compiled into style.css, so nothing needs adding to the .info file. It should add an entry if you pull in a JavaScript dependency.

**Comment by fender** [comment]
@justafish Ah I see. So I ran `grunt` but it doesn't seem to add Susy to `css/style.css`. Here is the file contents:

```
*, *:before, *:after {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box; }

/* generated with grunt-sass-globbing */
/* generated with grunt-sass-globbing */
/* generated with grunt-sass-globbing */
```

**Comment by justafish** [comment]
@fender It shouldn't compile things in that aren't being used, so you have to use some of the susy components first

**Comment by fender** [comment]
@justafish Aha! I never knew that. Nice :)

I created a `layout/_grid.scss` file as follows to test:
```
body {
  @include container(80em);
}
```

However, `style.css` seems to have outputted the contents twice:
```
*, *:before, *:after {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box; }

/* generated with grunt-sass-globbing */
body {
  max-width: 80em;
  margin-left: auto;
  margin-right: auto; }
  body:after {
    content: " ";
    display: block;
    clear: both; }

/* generated with grunt-sass-globbing */
/* generated with grunt-sass-globbing */
body {
  max-width: 80em;
  margin-left: auto;
  margin-right: auto; }
  body:after {
    content: " ";
    display: block;
    clear: both; }
```
