### ISSUE TITLE
Unable to install sass-mq via bower

### ISSUE THREAD

**Issue by mherchel** [Lullabot/windup#41]
I tried installing [Sass-MQ](https://github.com/sass-mq/sass-mq), and didn't have the scss downloaded into a vendor directory.

I tried `bower install sass-mq --save` per [the documentation](https://github.com/sass-mq/sass-mq#how-to-use-it)

**Comment by carwin** [comment]
Hmm... this sounds like an issue with wiredep. I'll take a look at it.

**Comment by carwin** [comment]
I installed this just fine. Saved into `bower_components`. Is this what you were saying didn't work?

**Comment by carwin** [comment]
@mherchel I re-read this issue while I was going through the list - I think you forgot the critical step of `grunt wiredep` to actually wire the dependencies. I just tested this locally to make sure and it does indeed import the `_mq.scss` file into the `scss/_vendor.scss` file.
