### ISSUE TITLE
What is grunt-contrib-clean doing?

### ISSUE THREAD

**Issue by mherchel** [Lullabot/windup#46]
I might just be an idiot on this one... but I'm unable to understand the purpose on this:

My understanding from https://github.com/gruntjs/grunt-contrib-clean, is that it will delete files and directories.

From what I see, it's deleting the following files:
````js
clean: {
      css: ['css/style.css', 'scss/_component.scss', 'scss/_layout.scss', 'scss/_skin.scss']
    },
````
Why is it deleting style.css?

It doesn't appear to be running within `grunt watch`. Should it be?
````javascript
watch: {
      css: {
        files: ['scss/**/*.scss'],
        tasks: ['sass_globbing', 'sass', 'postcss'],
        options: {
          livereload: true,
          spawn: false
        }
      }
    },
````
And within the default task, its running first. So, when the sass_globbing and sass processes run afterwards, it will recreate any files. 
````js
grunt.registerTask('default', ['clean','wiredep_create_bower', 'wiredep', 'sass_globbing', 'sass', 'postcss']);
````
Am I missing something here? Maybe a :beer:

**Comment by wesruv** [comment]
I've had a few :beers: and I'm where you're at. What is that doing?

Guessing this is @justafish, what was the intention?
https://github.com/Lullabot/windup/commit/71ec9c8759c874130b2d779775a13abfedc1aacf

**Comment by mdrummond** [comment]
The nice thing about contrib-clean is that it prevents any manual tweaking of CSS files from getting into the build. So every time a build is run, it is done from the same fresh state you would get the first time you run the build when everything is blank. Nice thing for consistency.

**Comment by justafish** [comment]
Yeah, that ^ :+1:

**Comment by mherchel** [comment]
haha
