### ISSUE TITLE
Create 8.0.x Branch

### ISSUE THREAD

**Issue by tlattimore** [Lullabot/windup#50]
It might be awhile before we start seeing a lot of requests for Drupal 8 sites. But I think it would be good to go ahead and create an D8 branch that we can start submitting  pull requests against. I think the name should be `8.0.x` to match Drupal Cores adoption of Semantic Versioning.

**Comment by tlattimore** [comment]
I went ahead and creating a branch for this that _exactly_ matches what is in `master`. So I opted not to submit a PR for it. I will get some peer review when I submit pull request for changes to this 

https://github.com/Lullabot/windup/tree/8.0.x

**Comment by carwin** [comment]
Cheers. Thanks for lookin' ahead.
