### ISSUE TITLE
SCSS Linter? SCSS Linter that doesn't require Ruby?

### ISSUE THREAD

**Issue by wesruv** [Lullabot/windup#56]
~~Looks like the interwebbins aren't helping in this department.~~

Putting a note in so maybe one day we'll get one of those bad fellas without a Ruby dependency.

**Comment by wesruv** [comment]
Hopefully this happens: https://github.com/sasstools/sass-lint

**Comment by carwin** [comment]
@wesruv it seems like sass-lint works but I haven't tried it. I'll work on putting something together.

**Comment by wesruv** [comment]
Last I heard the sass-lint npm package wasn't as feature robust as it's ruby cousin, but hopefully that's not the case now.

**Comment by carwin** [comment]
A good way to check this would be to go over to lullabot.com's repo and play around. I made a branch on that project to update to the sass-lint project, but there were some problems a few months ago. Not sure how it's developed since then.

**Comment by wesruv** [comment]
oooOOOOOoo. Will do!

**Comment by carwin** [comment]
So the To-do list here looks like

- [x] Remove csslint from 8.x branch
- [x] Remove csslint from 7.x branch
- [x] Set up sass-lint for 8.x branch
- [ ] Set up sass-lint for 7.x branch
- [ ] Decide if good.

**Comment by carwin** [comment]
There's a pull request open for sass-lint on the 8.x branch @wesruv.

**Comment by carwin** [comment]
Well with lack of further ado, I pronounce this good. The rules themselves may require some tweaking as we get used to them.
