### ISSUE TITLE
[Re: #55] Migrate any template.php functionality that is still needed

### ISSUE THREAD

**Issue by wesruv** [Lullabot/windup#58]
Here's the current status:
- [x] template_preprocess_html() - _wes_ - **PR: https://github.com/Lullabot/windup/pull/70**
- [x] template_preprocess_node() - _carwin_ - **PR: https://github.com/Lullabot/windup/pull/87**
- [x] template_preprocess_entity() *this doesn't seem to exist in D8?*
- [x] template_preprocess_taxonomy_term() - _carwin_ **PR: https://github.com/Lullabot/windup/pull/90**
- [x] template_preprocess_user_profile - _carwin_ **PR: https://github.com/Lullabot/windup/pull/88**
- [x] template_preprocess_comment - _carwin_ **PR: https://github.com/Lullabot/windup/pull/89**
- [x] template_page_alter - _carwin_ - Can't do it. We need these new wrappers for contextual links to work.
- [x] Remove classes utility - _carwin_ - Don't need it, we can use templates, and D8 has some good ones already.
- [x] Default Template Suggestions helper function - _carwin_ - see #87. We don't really need this as much.

**Comment by carwin** [comment]
@wesruv I've assigned this to both of us to work on and tagged each of the tasks with one of us.
