### ISSUE TITLE
[Re: #55] Retire old D7 files

### ISSUE THREAD

**Issue by wesruv** [Lullabot/windup#61]
Going to leave them in with `.bak` extension for reference until we get a proper `8.0.x` version of the theme.

**Comment by wesruv** [comment]
PR Here: https://github.com/Lullabot/windup/pull/63

**Comment by carwin** [comment]
These files have been retired but not totally deleted from the branch. I'm not sure how keeping them around helps us (since we could always just reference the 7.x branch), but I'll let you decide when to close this one @wesruv.

**Comment by wesruv** [comment]
lol, laziness? We should probably kill them.

**Comment by carwin** [comment]
Okay, I'll kill it
