### ISSUE TITLE
some node modules include .info file that breaks site

### ISSUE THREAD

**Issue by krisbulman** [Lullabot/windup#71]
As we all know, malformed theme.info files really break the site. See https://www.drupal.org/node/619542

The new issue for the core patch for 7.x is https://www.drupal.org/node/2329453

As it happens, some node_modules, like ```grunt-eslint``` include an ```lcov.info``` file that makes drupal [shit the bed](https://gist.github.com/krisbulman/38b0e0af43b35e5e0b72). This is going to be a pain point for a lot of people (like it has been for myself for 2 hours of backtracking).

**Comment by krisbulman** [comment]
This might work

```
"scripts": {
  "postinstall": "find node_modules/ -name '*.info' -type f -delete"
}
```

**Comment by mdrummond** [comment]
Yes, I've been using that postinstall line and it does the trick.

**Comment by krisbulman** [comment]
@carwin this is patched in 8, not in 7.

**Comment by krisbulman** [comment]
Disregard, of course patches don't make it into core in a timely manner :angry:

**Comment by carwin** [comment]
Looks like this has been patched for D7 in the last link you posted @krisbulman, is there anything to do here?

**Comment by krisbulman** [comment]
whoa shit, cool a committed patch to 7. all good, close out
