### ISSUE TITLE
Is there any way to grunt-usemin integration?

### ISSUE THREAD

**Issue by jackncoke** [Lullabot/windup#72]
Hi guys, I have a question about theme deployment.

**bower** and **wiredep** modules works quite nicely, I add a lot of content this way! however, now I have to combine these files such as _bundle.js_, _bundle.css_ etc... **grunt-usemin** module works very well for this purpose, but I could not find an integration for Theme info file.  Waiting for your help in this regard.

Thank you.

**Comment by carwin** [comment]
I'm not familiar enough to be of any help here, maybe @justafish has an idea?

I'll link to the stackoverflow post here too, just in case some info shows up there: http://stackoverflow.com/questions/32343351/grunt-usemin-integration-for-custom-file-types
