### ISSUE TITLE
Potentially Remove csslint

### ISSUE THREAD

**Issue by carwin** [Lullabot/windup#74]
I don't see a reason to lint compiled code and I misunderstood what was happening when I merged the code. Discuss.

**Comment by krisbulman** [comment]
i vote either removing it completely, or replacing with scss-lint. if scss-lint is added to a test command in grunt, only run it if you want to, and have your ci tool run it if you want to.

**Comment by wesruv** [comment]
Late to the party, it's worth trying out the node sass-linter is awesome: https://www.npmjs.com/package/sass-lint

Looks like they've been cranking on it, but I haven't tried it. 

If not I vote scss-lint.

If we're not writing a compiler, I don't see why we'd lint CSS. If there's a feature missing from our SCSS/Sass linter, we should try to help fix it there.

**Comment by carwin** [comment]
For now I've just removed it. I want to avoid using scss-lint because of the Ruby dependency. If sass-lint turns out to be acceptable, we'll put that in. For now let's leave linting on a case-by-case basis until we discover something we can all get behind.
